spring:
  profiles:
    include: db
  datasource:
    username: ${username}
    password: ${password}
    driver-class-name: ${driver-class-name}
    url: ${url}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false